### ISSUE TITLE
Wrong url generation

### ISSUE THREAD

**Issue by Gallax** [juliomotol/lapiv#1]
in api.php
 Route::lapiv()->get('/foo-controller', [FooGatewayController::class, 'index']);

produces this route
GET|HEAD | v{version}/api/foo-controller

instead of this:
GET|HEAD | api/v{version}/foo-controller

using laravel/laravel (v8.5.23)

**Comment by juliomotol** [comment]
Can you share your `config/lapiv.php` and the `boot()` method in `App\Providers\RouteServiceProvider`.

**Comment by Gallax** [comment]
I didn't change these files.

App\Providers\RouteServiceProvider:
    public function boot()
    {
        $this->configureRateLimiting();

        $this->routes(function () {
            Route::prefix('api')
                ->middleware('api')
                ->namespace($this->namespace)
                ->group(base_path('routes/api.php'));

            Route::middleware('web')
                ->namespace($this->namespace)
                ->group(base_path('routes/web.php'));
        });
    }

**Comment by juliomotol** [comment]
is `Route::lapiv()` being grouped?

**Comment by Gallax** [comment]
No, it is at the root level of api.php

**Comment by juliomotol** [comment]
This seems to be a bug with Laravel's Router.

Given in the `RouteServiceProvider`, it applies a prefix and groups it. Then within that group, when doing another `prefix()` it prepends it to the instead of appending it.

```php
Route::prefix('first')->group(function () {
    Route::prefix('second')->get('foo', [FooGatewayController::class, 'index']);
});

// Generates `second/first/foo` instead of `first/second/foo`.
```

In our case, `Route::lapiv()` is a shorthand for `Route::prefix('v{version}')` when using `uri` versioning.

I'll be sending a bug report to Laravel regarding this. For the meantime, Please use the the ff syntax:

```php
Route::lapiv(function () {
    Route::get('foo', [FooGatewayController::class, 'index']);
});
```

I'll be updating the docs, thanks!
